name: Build Blog Page
run-name: ${{ github.actor }} Deply Blog for yoshio.dev 🚀
on:
  push:
    branches:
      - master
  workflow_dispatch:
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
          token: ${{ secrets.ACCESS_TOKEN }}
          submodules: true
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'
          architecture: 'x64'
      - name: Setup Python Env
        run: pip3 install pelican markdown ghp-import \
      - name: ls command
        run: cd themes/elegant/
      - name: ls2 command
        run: ls -al
      - name: Delete search function
        run: cd themes/elegant/templates |
          ls -al |
          sed '/<li><form class="navbar-search"/d' base.html > base_new.html |
          mv base_new.html base.html |
          cat base.html |
          cd ../../../ \
      - name: Run Pelican build
        run: make clean |
          make html \
      - name: Run Pelican Publish
        run: make publish
      - name: make output folder
        run: ghp-import output
      - name: Publish blog page
        run: |
          git remote set-url origin https://github-actions:${GITHUB_TOKEN}@github.com/${GITHUB_REPOSITORY}
          git config --global user.name "${GITHUB_ACTOR}"
          git config --global user.email "${GITHUB_ACTOR}@users.noreply.github.com"
          git push origin gh-pages; \
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
